export const TABLE_DATA = [
  {
    title: "Insurance",
    description: "Property Coverage",
    account: "LTC Wallet",
    balance: "-$4.012",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon1.svg",
    color: "red",
  },
  {
    title: "Electricity",
    description: "Utility Payment",
    account: "BTC Wallet",
    balance: "-$2.092",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon2.svg",
    color: "red",
  },
  {
    title: "Omar Griffith ",
    description: "Utility Payment ",
    account: "ETH Wallet ",
    balance: "+$1.089 ",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon3.svg",
    color: "green",
  },
  {
    title: "Electricity",
    description: "Utility Payment ",
    account: "BTC Wallet ",
    balance: " -$833",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon4.svg",
    color: "red",
  },
  {
    title: "Insurance ",
    description: " Property Coverage",
    account: "BTC Wallet ",
    balance: "-$1.458 ",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon5.svg",
    color: "red",
  },
  {
    title: "Nettie Barnett ",
    description: "Property Coverage ",
    account: "LTC Wallet ",
    balance: " +$1.089",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon6.svg",
    color: "green",
  },
  {
    title: "Junaid Horn ",
    description: " Property Coverage",
    account: "ETH Wallet",
    balance: "+$1.089 ",
    dateFrom: "Mon, 20 May - 01:10",
    dateTo: "Mon, 25 May - 01:10",
    image: "/assets/admin/analytics-dashboard/table-icon7.svg",
    color: "red",
  },
];
